<a href="https://colab.research.google.com/github/Vishnu-1203/Neural-Network-From-Scratch/blob/main/Neural_network_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [116]:
train=pd.read_csv("/content/mnist_train.csv")
test=pd.read_csv("/content/mnist_test.csv")

train=np.array(train)
test=np.array(test)

m,n=train.shape

Splitting Data

---



In [117]:
y_train=train[:,0]
x_train=(train[:,1:]/255).T

y_test=test[:,0]
x_test=(test[:,1:]/255).T


print(x_train.shape)
print(y_train.shape)

(784, 60000)
(60000,)


Initializing Parameters and Forward Propogation


---



In [118]:
def init_params():
  w1=np.random.rand(10,784)-0.5
  b1=np.random.rand(10,1)-0.5

  w2=np.random.rand(10,10)-0.5
  b2=np.random.rand(10,1)-0.5

  return w1,b1,w2,b2

w1,b1,w2,b2=init_params()

def ReLu(Z):
  return np.maximum(0,Z)

def softmax(Z):
  return np.exp(Z)/np.sum(np.exp(Z))
def forward_prop(w1,b1,w2,b2,x):
  a1=w1.dot(x)+b1
  z1=ReLu(a1)
  z2=w2.dot(a1)+b2
  a2=softmax(z2)
  return z1,a1,z2,a2



Backward Propogation

---



In [119]:
def one_hot(y):
  one_hot_y=np.zeros((y.size,y.max()+1))
  one_hot_y[np.arange(y.size),y]=1
  return one_hot_y.T

def deriv_ReLu(Z):
  return Z>0



In [120]:
def backward_prop(z1,a1,z2,a2,w1,w2,x,y):
  one_hot_y=one_hot(y)

  dz2=a2-one_hot_y
  dw2=1/m*dz2.dot(a1.T)
  db2=1/m*(np.sum(dz2))

  dz1=w2.T.dot(dz2)*deriv_ReLu(z1)
  dw1=1/m*dz1.dot(x.T)
  db1=1/m*(np.sum(dz1))

  return dw1,db1,dw2,db2



Updating parameters

---





In [121]:
def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
  w2=w2-alpha*dw2
  b2=b2-alpha*db2
  w1=w1-alpha*dw1
  b1=b1-alpha*db1
  return w1,b1,w2,b2

Gradient Descent

---



In [122]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(x,y,iterations,alpha):
  w1,b1,w2,b2=init_params()
  for i in range(iterations):
    z1,a1,z2,a2=forward_prop(w1,b1,w2,b2,x)
    dw1,db1,dw2,db2=backward_prop(z1,a1,z2,a2,w1,w2,x,y)
    w1,b1,w2,b2=update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)
    if(i%10==0):
      print("Epoch:",i)
      print("Accuracy:",get_accuracy(get_predictions(a2),y))

  return w1,b1,w2,b2


In [123]:
W1,B1,W2,B2=gradient_descent(x_train,y_train,100,0.1)

Epoch: 0
[5 5 5 ... 7 5 5] [5 0 4 ... 5 6 8]
Accuracy: 0.07696666666666667
Epoch: 10
[5 0 5 ... 5 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.1243


/tmp/ipython-input-1083027146.py:16: RuntimeWarning: overflow encountered in exp
  return np.exp(Z)/np.sum(np.exp(Z))
/tmp/ipython-input-1083027146.py:16: RuntimeWarning: invalid value encountered in divide
  return np.exp(Z)/np.sum(np.exp(Z))


Epoch: 20
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 30
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 40
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 50
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 60
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 70
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 80
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
Epoch: 90
[0 0 0 ... 0 0 0] [5 0 4 ... 5 6 8]
Accuracy: 0.09871666666666666
